name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-go-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
          
      - name: Install dependencies
        run: |
          cd backend
          go mod download
          
      - name: Build Go backend for ARM64
        run: |
          cd backend
          GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o ../digital-photo-frame-arm64 .
          
      - name: Upload Go binary
        uses: actions/upload-artifact@v4
        with:
          name: go-backend-arm64
          path: digital-photo-frame-arm64

  build-arm64-tauri:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Build ARM64 app using arm-runner
        uses: pguyot/arm-runner-action@v2.6.5
        with:
          base_image: https://dietpi.com/downloads/images/DietPi_RPi5-ARMv8-Bookworm.img.xz
          cpu: cortex-a72
          bind_mount_repository: true
          image_additional_mb: 10240
          optimize_image: no
          commands: |
            # Install dependencies
            apt-get update -y --allow-releaseinfo-change
            apt-get install -y curl build-essential libssl-dev pkg-config \
              libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev \
              librsvg2-dev
            
            # Install Node.js
            curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
            apt-get install -y nodejs
            
            # Install Rust
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            . ~/.cargo/env
            
            # Build Tauri frontend
            cd frontend
            npm install
            npm run tauri build
            
      - name: Upload Tauri binary
        uses: actions/upload-artifact@v4
        with:
          name: tauri-frontend-arm64
          path: frontend/src-tauri/target/release/photo-frame

  create-debian-package:
    runs-on: ubuntu-latest
    needs: [build-go-backend, build-arm64-tauri]
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          
      - name: Install packaging tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev rubygems build-essential
          sudo gem install fpm
          
      - name: Create Debian package
        run: |
          # Create package structure
          mkdir -p package-root/opt/photoframe
          mkdir -p package-root/etc/photoframe
          mkdir -p package-root/usr/bin
          
          # Copy Go backend binary
          cp digital-photo-frame-arm64 package-root/opt/photoframe/digital-photo-frame-aarch64
          
          # Copy Tauri frontend binary
          cp photo-frame package-root/opt/photoframe/photo-frame-frontend
          chmod +x package-root/opt/photoframe/photo-frame-frontend
          
          # Copy config and wrapper
          cp backend/config.yaml.example package-root/etc/photoframe/config.yaml
          cp packaging/wrapper/digital-photo-frame package-root/usr/bin/
          chmod +x package-root/usr/bin/digital-photo-frame
          
          # Build Debian package
          VERSION=${GITHUB_REF#refs/tags/v}
          if [ -z "$VERSION" ] || [ "$VERSION" = "$GITHUB_REF" ]; then
            VERSION="0.0.0-$(date +%Y%m%d%H%M%S)"
          fi
          
          fpm -s dir -t deb -n photoframe-pi64 -v "$VERSION" \
            --architecture arm64 \
            --depends "libc6" \
            --description "Digital Photo Frame for Raspberry Pi 64-bit" \
            --url "https://github.com/${{ github.repository }}" \
            --maintainer "${{ github.actor }}" \
            --license "MIT" \
            --after-install packaging/debian/postinst \
            -C package-root \
            opt etc usr
            
      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: debian-package
          path: "*.deb"
          
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: "*.deb"
          body: |
            ## Digital Photo Frame - ARM64
            
            ### Installation
            ```bash
            wget photoframe-pi64_*.deb
            sudo apt install ./photoframe-pi64_*.deb
            ```
            
            ### Usage
            ```bash
            # Run backend
            cd /etc/photoframe && digital-photo-frame
            
            # Run frontend
            /opt/photoframe/photo-frame-frontend --fullscreen
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}