name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-go-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
          
      - name: Install dependencies
        run: |
          cd backend
          go mod download
          
      - name: Build Go backend for ARM64
        run: |
          cd backend
          GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o ../digital-photo-frame-arm64 .
          
      - name: Upload Go binary
        uses: actions/upload-artifact@v4
        with:
          name: go-backend-arm64
          path: digital-photo-frame-arm64

  publish-tauri:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: install dependencies (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: install frontend dependencies
        run: |
          cd frontend
          npm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CC_aarch64_unknown_linux_gnu: aarch64-linux-gnu-gcc
          CXX_aarch64_unknown_linux_gnu: aarch64-linux-gnu-g++
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
        with:
          projectPath: frontend
          tagName: app-v__VERSION__
          releaseName: "Digital Photo Frame v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: --target aarch64-unknown-linux-gnu

  create-debian-package:
    runs-on: ubuntu-22.04
    needs: [build-go-backend, publish-tauri]
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Go backend
        uses: actions/download-artifact@v4
        with:
          name: go-backend-arm64
          
      - name: Install packaging tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev rubygems build-essential
          sudo gem install fpm
          
      - name: Create Debian package
        run: |
          # Create package structure
          mkdir -p package-root/opt/photoframe
          mkdir -p package-root/etc/photoframe
          mkdir -p package-root/usr/bin
          
          # Copy Go backend binary
          cp digital-photo-frame-arm64 package-root/opt/photoframe/digital-photo-frame-aarch64
          
          # Copy config and wrapper
          cp backend/config.yaml.example package-root/etc/photoframe/config.yaml
          cp packaging/wrapper/digital-photo-frame package-root/usr/bin/
          chmod +x package-root/usr/bin/digital-photo-frame
          
          # Build Debian package
          VERSION=${GITHUB_REF#refs/tags/v}
          if [ -z "$VERSION" ] || [ "$VERSION" = "$GITHUB_REF" ]; then
            VERSION="0.0.0-$(date +%Y%m%d%H%M%S)"
          fi
          
          fpm -s dir -t deb -n photoframe-pi64 -v "$VERSION" \
            --architecture arm64 \
            --depends "libc6" \
            --description "Digital Photo Frame for Raspberry Pi 64-bit" \
            --url "https://github.com/${{ github.repository }}" \
            --maintainer "${{ github.actor }}" \
            --license "MIT" \
            --after-install packaging/debian/postinst \
            -C package-root \
            opt etc usr
            
      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: debian-package
          path: "*.deb"