name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-deb:
    runs-on: ubuntu-24.04-arm
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
        
    - name: Install packaging tools
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby ruby-dev rubygems build-essential
        sudo gem install fpm
        
    - name: Install Tauri 1.5 compatible dependencies
      run: |
        sudo apt-get install -y \
          pkg-config \
          libssl-dev \
          libwebkit2gtk-4.1-dev \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          libsoup-3.0-dev
        
    - name: Build Go backend
      run: |
        cd backend
        go mod tidy
        go build -ldflags="-s -w" -o ../digital-photo-frame-arm64 .
        
    - name: Build Tauri frontend
      run: |
        cd frontend
        npm ci
        npm run tauri build
        
        
    - name: Prepare package structure
      run: |
        mkdir -p package-root/opt/photoframe
        mkdir -p package-root/etc/photoframe
        mkdir -p package-root/usr/bin
        
        # Copy Tauri frontend binary
        cp frontend/src-tauri/target/release/photo-frame-frontend package-root/opt/photoframe/
        
        # Copy config template
        cp backend/config.yaml.example package-root/etc/photoframe/config.yaml
        
        # Copy wrapper script
        cp packaging/wrapper/digital-photo-frame package-root/usr/bin/
        chmod +x package-root/usr/bin/digital-photo-frame
        
        
    - name: Build Pi 64-bit package (ARM64)
      run: |
        # Copy ARM64 binary
        cp digital-photo-frame-arm64 package-root/opt/photoframe/digital-photo-frame-aarch64
        
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "Building version: $VERSION"
        fpm -s dir -t deb -n photoframe-pi64 -v "$VERSION" \
          --architecture arm64 \
          --depends "libc6" \
          --description "Digital Photo Frame for Raspberry Pi 64-bit" \
          --url "https://github.com/${{ github.repository }}" \
          --maintainer "${{ github.actor }}" \
          --license "MIT" \
          -C package-root \
          opt etc usr
        
    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: debian-packages
        path: "*.deb"
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: "*.deb"
        body: |
          ## Digital Photo Frame - ARM64 Only
          
          Simplified release for Raspberry Pi 64-bit OS.
          
          ### Installation
          ```bash
          # Download and install
          wget photoframe-pi64_*.deb
          sudo apt install ./photoframe-pi64_*.deb
          ```
          
          ### Configuration
          ```bash
          # Edit config
          sudo nano /etc/photoframe/config.yaml
          ```
          
          ### Manual Usage
          ```bash
          # Run backend
          cd /etc/photoframe && digital-photo-frame
          
          # Run frontend (fullscreen)
          /opt/photoframe/photo-frame-frontend --fullscreen
          ```
          
          ### Access
          Web interface: `http://your-pi-ip:8080`
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}